services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Rj0Q8]o@W<-Oy21Y
      - POSTGRES_DB=exceldb
    ports:
      - '7240:5432'
    volumes:
      - db:/var/lib/postgresql/data

  web:
    env_file:
      - .env
    environment:
      - DB_NAME=exceldb
      - DB_USER_NAME=postgres
      - DB_PASSWORD=Rj0Q8]o@W<-Oy21Y
      - DB_HOST_NAME=db
      - DB_PORT=5432
    build: .
    volumes:
      - .:/app
    ports:
      - "127.0.0.1:8000:8000"
    depends_on:
      - db

volumes:
  db:
    driver: local
